from tkinter import *
from tkinter import messagebox
from PIL import ImageTk , Image
import tempfile
from tkinter import ttk
import os,sys

root=Tk()
root.title('Normal Billing')
root.geometry("1080x640+0+0")
bg_color='#2D9290'
root['bg']='#0f0f0f'
madeby=Label(root,text='Made By : Abdul',font=("Times New Roman" ,11,'bold'),fg='#2092cb',bg='#3f3f3f')
madeby.place(x=80,y=617)

#=====================variables===================
Bread=StringVar()
Total2=DoubleVar()
Total3=DoubleVar()
Total1=DoubleVar()

Date=StringVar()
Month=StringVar()
Year=StringVar()

mc1=DoubleVar()
mc2=DoubleVar()
mc3=DoubleVar()
mc4=DoubleVar()
mc5=DoubleVar()
mc6=DoubleVar()
mc7=DoubleVar()
mc8=DoubleVar()
mc9=DoubleVar()
mc10=DoubleVar()
mc11=DoubleVar()
mc12=DoubleVar()
mc13=DoubleVar()
mc14=DoubleVar()
mc15=DoubleVar()
mc16=DoubleVar()

f1=DoubleVar()
f2=DoubleVar()
f3=DoubleVar()
f4=DoubleVar()
f5=DoubleVar()
f6=DoubleVar()
f7=DoubleVar()
f8=DoubleVar()
f9=DoubleVar()
f10=DoubleVar()
f11=DoubleVar()
f12=DoubleVar()
f13=DoubleVar()
f14=DoubleVar()
f15=DoubleVar()
f16=DoubleVar()

a1=IntVar()
a2=IntVar()
a3=IntVar()
a4=IntVar()
a5=IntVar()
a6=IntVar()
a7=IntVar()
a8=IntVar()
a9=IntVar()
a10=IntVar()
a11=IntVar()
a12=IntVar()
a13=IntVar()
a14=IntVar()
a15=IntVar()
a16=IntVar()

w1=DoubleVar()
w2=DoubleVar()
w3=DoubleVar()
w4=DoubleVar()
w5=DoubleVar()
w6=DoubleVar()
w7=DoubleVar()
w8=DoubleVar()
w9=DoubleVar()
w10=DoubleVar()
w11=DoubleVar()
w12=DoubleVar()
w13=DoubleVar()
w14=DoubleVar()
w15=DoubleVar()
w16=DoubleVar()

t1=DoubleVar()
t2=DoubleVar()
t3=DoubleVar()
t4=DoubleVar()
t5=DoubleVar()
t6=DoubleVar()
t7=DoubleVar()
t8=DoubleVar()
t9=DoubleVar()
t10=DoubleVar()
t11=DoubleVar()
t12=DoubleVar()
t13=DoubleVar()
t14=DoubleVar()
t15=DoubleVar()
t16=DoubleVar()

i1=StringVar()
i2=StringVar()
i3=StringVar()
i4=StringVar()
i5=StringVar()
i6=StringVar()
i7=StringVar()
i8=StringVar()
i9=StringVar()
i10=StringVar()
i11=StringVar()
i12=StringVar()
i13=StringVar()
i14=StringVar()
i15=StringVar()
i16=StringVar()

mm1=IntVar()
mm2=IntVar()
mm3=IntVar()
mm4=IntVar()
mm5=IntVar()
mm6=IntVar()
mm7=IntVar()
mm8=IntVar()
mm9=IntVar()
mm10=IntVar()
mm11=IntVar()
mm12=IntVar()
mm13=IntVar()
mm14=IntVar()
mm15=IntVar()
mm16=IntVar()

cw=StringVar()
cr=StringVar()
cg=StringVar()

total_cost=StringVar()
# ===========Function===============
def total():
    if Bread.get()=='' and i1.get()=='' :
        messagebox.showerror('ERROR','   PLEASE ENTER AMOUNT & DATA        ')
    else:
               
        r1=a1.get()
        r2=a2.get()
        r3=a3.get()
        r4=a4.get()
        r5=a5.get()
        r6=a6.get()
        r7=a7.get()
        r8=a8.get()
        r9=a9.get()
        r10=a10.get()
        r11=a11.get()
        r12=a12.get()
        r13=a13.get()
        r14=a14.get()
        r15=a15.get()
        r16=a16.get()
                    
        Total3.set(r1+r2+r3+r4+r5+r6+r7+r8+r9+r10+r11+r12+r13+r14+r15+r16)
                
        """
        f2.set(str(round((t2.get()*w2.get()/100),2)))
        f3.set(str(round((t3.get()*w3.get()/100),2)))
        f4.set(str(round((t4.get()*w4.get()/100),2)))
        f5.set(str(round((t5.get()*w5.get()/100),2)))
        f6.set(str(round((t6.get()*w6.get()/100),2)))
        f7.set(str(round((t7.get()*w7.get()/100),2)))
        f8.set(str(round((t8.get()*w8.get()/100),2)))
        f9.set(str(round((t9.get()*w9.get()/100),2)))
        f10.set(str(round((t10.get()*w10.get()/100),2)))
        f11.set(str(round((t11.get()*w11.get()/100),2)))
        f12.set(str(round((t12.get()*w12.get()/100),2)))
        f13.set(str(round((t13.get()*w13.get()/100),2)))
        f14.set(str(round((t14.get()*w14.get()/100),2)))
        f15.set(str(round((t15.get()*w15.get()/100),2)))
        f16.set(str(round((t16.get()*w16.get()/100),2)))
        """
        #1f
        if (w1.get())==0:
          f1.set(str(round(f1.get(),2)))
        elif (w1.get())>0 :
          f1.set(str(round((t1.get()*w1.get()/100),2)))
          #2f
        if (w2.get())==0:
          f2.set(str(round(f2.get(),2)))
        elif (w2.get())>0 :
          f2.set(str(round((t2.get()*w2.get()/100),2)))
        #3f
        if (w3.get())==0:
          f3.set(str(round(f3.get(),2)))
        elif (w3.get())>0 :
          f3.set(str(round((t3.get()*w3.get()/100),2)))
        #4f
        if (w4.get())==0:
          f4.set(str(round(f4.get(),2)))
        elif (w4.get())>0 :
          f4.set(str(round((t4.get()*w4.get()/100),2)))
        #5f
        if (w5.get())==0:
          f5.set(str(round(f5.get(),2)))
        elif (w5.get())>0 :
          f5.set(str(round((t5.get()*w5.get()/100),2)))
        #6f
        if (w6.get())==0:
          f6.set(str(round(f6.get(),2)))
        elif (w6.get())>0 :
          f6.set(str(round((t6.get()*w6.get()/100),2)))
        #7f
        if (w7.get())==0:
          f7.set(str(round(f7.get(),2)))
        elif (w7.get())>0 :
          f7.set(str(round((t7.get()*w7.get()/100),2)))
        #8f
        if (w8.get())==0:
          f8.set(str(round(f8.get(),2)))
        elif (w8.get())>0 :
          f8.set(str(round((t8.get()*w8.get()/100),2)))
        #9f
        if (w9.get())==0:
          f9.set(str(round(f9.get(),2)))
        elif (w9.get())>0 :
          f9.set(str(round((t9.get()*w9.get()/100),2)))
        #10f
        if (w10.get())==0:
          f10.set(str(round(f10.get(),2)))
        elif (w10.get())>0 :
          f10.set(str(round((t10.get()*w10.get()/100),2)))
        #11f
        if (w11.get())==0:
          f11.set(str(round(f11.get(),2)))
        elif (w11.get())>0 :
          f11.set(str(round((t11.get()*w11.get()/100),2)))
        #12f
        if (w12.get())==0:
          f12.set(str(round(f12.get(),2)))
        elif (w12.get())>0 :
          f12.set(str(round((t12.get()*w12.get()/100),2)))
        #13f
        if (w13.get())==0:
          f13.set(str(round(f13.get(),2)))
        elif (w13.get())>0 :
          f13.set(str(round((t13.get()*w13.get()/100),2)))
        #14f
        if (w14.get())==0:
          f14.set(str(round(f14.get(),2)))
        elif (w14.get())>0 :
          f14.set(str(round((t14.get()*w14.get()/100),2)))
        #15f
        if (w15.get())==0:
          f15.set(str(round(f15.get(),2)))
        elif (w15.get())>0 :
          f15.set(str(round((t15.get()*w15.get()/100),2)))
        #16f
        if (w16.get())==0:
          f16.set(str(round(f16.get(),2)))
        elif (w16.get())>0 :
          f16.set(str(round((t16.get()*w16.get()/100),2)))
        
        """
        b=f2.get()
        c=f3.get()
        d=f4.get()
        e=f5.get()
        f=f6.get()
        g=f7.get()
        h=f8.get()
        i=f9.get()
        j=f10.get()
        k=f11.get()
        l=f12.get()
        k=f13.get()
        m=f14.get()
        n=f15.get()
        o=f16.get()
        """
        Total2.set(f1.get()+f2.get()+f3.get()+f4.get()+f5.get()+f6.get()+f7.get()+f8.get()+f9.get()+f10.get()+f11.get()+f12.get()+f13.get()+f14.get()+f15.get()+f16.get())
        

        mc1.set(str(round((mm1.get()*w1.get()/1000),2)))
        mc2.set(str(round((mm2.get()*w2.get()/1000),2)))
        mc3.set(str(round((mm3.get()*w3.get()/1000),2)))
        mc4.set(str(round((mm4.get()*w4.get()/1000),2)))
        mc5.set(str(round((mm5.get()*w5.get()/1000),2)))
        mc6.set(str(round((mm6.get()*w6.get()/1000),2)))
        mc7.set(str(round((mm7.get()*w7.get()/1000),2)))
        mc8.set(str(round((mm8.get()*w8.get()/1000),2)))
        mc9.set(str(round((mm9.get()*w9.get()/1000),2)))
        mc10.set(str(round((mm10.get()*w10.get()/1000),2)))
        mc11.set(str(round((mm11.get()*w11.get()/1000),2)))
        mc12.set(str(round((mm12.get()*w12.get()/1000),2)))
        mc13.set(str(round((mm13.get()*w13.get()/1000),2)))
        mc14.set(str(round((mm14.get()*w14.get()/1000),2)))
        mc15.set(str(round((mm15.get()*w15.get()/1000),2)))
        mc16.set(str(round((mm16.get()*w16.get()/1000),2)))

        mk1=mc1.get()
        mk2=mc2.get()
        mk3=mc3.get()
        mk4=mc4.get()
        mk5=mc5.get()
        mk6=mc6.get()
        mk7=mc7.get()
        mk8=mc8.get()
        mk9=mc9.get()
        mk10=mc10.get()
        mk11=mc12.get()
        mk12=mc12.get()
        mk13=mc13.get()
        mk14=mc14.get()
        mk15=mc15.get()
        mk16=mc16.get()

        Total1.set(mk1+mk2+mk3+mk4+mk5+mk6+mk7+mk8+mk9+mk10+mk11+mk12+mk13+mk14+mk15+mk16)


        
def receipt():
        
    textarea.delete(1.0,END)     
    textarea.insert(1.10,f'"»»-——————————————— O M ——————————————-««"\n')  
    textarea.insert(END,f'    || Sri Ganeshaya Namaha ||\t\t       \t|| Sri Siddhanath Prasanna ||\n ')
    textarea.insert(END,'\t\t\t       ESTIMATE ') 
    textarea.insert(END,f'\n Name : {Bread.get()}')
    textarea.insert(END,f'\n Date : {Date.get()}/{Month.get()}/ {Year.get()}')
    textarea.insert(END,'\n ____________________________________________________________________\n')
    textarea.insert(END,'|   MC\t| MC/kg.\t|          Items Name\t|Wt.\tx touch      |     Fine    |  Cash  |\n')
    textarea.insert(END,'|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|\n')
    if i1.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
    elif a2.get()<=0 :
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
    elif i3.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
    elif a4.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
    elif i5.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
    elif a6.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
    elif i7.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
    elif a8.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
    elif i9.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
    elif a10.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
    elif i11.get()<'':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
    elif a12.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
        textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}\t x {t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
    elif i13.get()<='':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
        textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}\t x {t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
        textarea.insert(END,f'|{mc13.get()}\t|{mm13.get()}\t|{i13.get()}\t\t|{w13.get()}\t x {t13.get()}\t|{f13.get()}\t|{a13.get()}\n')
    elif a14.get()<=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
        textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}\t x {t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
        textarea.insert(END,f'|{mc13.get()}\t|{mm13.get()}\t|{i13.get()}\t\t|{w13.get()}\t x {t13.get()}\t|{f13.get()}\t|{a13.get()}\n')
        textarea.insert(END,f'|{mc14.get()}\t|{mm14.get()}\t|{i14.get()}\t\t|{w14.get()}\t x {t14.get()}\t|{f14.get()}\t|{a14.get()}\n')
    elif i15.get()<'':
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
        textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}\t x {t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
        textarea.insert(END,f'|{mc13.get()}\t|{mm13.get()}\t|{i13.get()}\t\t|{w13.get()}\t x {t13.get()}\t|{f13.get()}\t|{a13.get()}\n')
        textarea.insert(END,f'|{mc14.get()}\t|{mm14.get()}\t|{i14.get()}\t\t|{w14.get()}\t x {t14.get()}\t|{f14.get()}\t|{a14.get()}\n')
        textarea.insert(END,f'|{mc15.get()}\t|{mm15.get()}\t|{i15.get()}\t\t|{w15.get()}\t x x{t15.get()}\t|{f15.get()}\t|{a15.get()}\n')
    elif a16.get()>=0:
        textarea.insert(END,f'|{mc1.get()}\t|{mm1.get()}\t|{i1.get()}\t\t|{w1.get()}\t x {t1.get()}\t|{f1.get()}\t|{a1.get()}\n')
        textarea.insert(END,f'|{mc2.get()}\t|{mm2.get()}\t|{i2.get()}\t\t|{w2.get()}\t x {t2.get()}\t|{f2.get()}\t|{a2.get()}\n')
        textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}\t x {t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
        textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}\t x {t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
        textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}\t x {t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
        textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}\t x {t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
        textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}\t x {t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
        textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}\t x {t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
        textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}\t x {t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
        textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}\t x {t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
        textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}\t x {t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
        textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}\t x {t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
        textarea.insert(END,f'|{mc13.get()}\t|{mm13.get()}\t|{i13.get()}\t\t|{w13.get()}\t x {t13.get()}\t|{f13.get()}\t|{a13.get()}\n')
        textarea.insert(END,f'|{mc14.get()}\t|{mm14.get()}\t|{i14.get()}\t\t|{w14.get()}\t x {t14.get()}\t|{f14.get()}\t|{a14.get()}\n')
        textarea.insert(END,f'|{mc15.get()}\t|{mm15.get()}\t|{i15.get()}\t\t|{w15.get()}\t x {t15.get()}\t|{f15.get()}\t|{a15.get()}\n')
        textarea.insert(END,f'|{mc16.get()}\t|{mm16.get()}\t|{i16.get()}\t\t|{w16.get()}\t x {t16.get()}\t|{f16.get()}\t|{a16.get()}\n')
    
    """
    textarea.insert(END,f'|{mc3.get()}\t|{mm3.get()}\t|{i3.get()}\t\t|{w3.get()}x{t3.get()}\t|{f3.get()}\t|{a3.get()}\n')
    textarea.insert(END,f'|{mc4.get()}\t|{mm4.get()}\t|{i4.get()}\t\t|{w4.get()}x{t4.get()}\t|{f4.get()}\t|{a4.get()}\n')
    textarea.insert(END,f'|{mc5.get()}\t|{mm5.get()}\t|{i5.get()}\t\t|{w5.get()}x{t5.get()}\t|{f5.get()}\t|{a5.get()}\n')
    textarea.insert(END,f'|{mc6.get()}\t|{mm6.get()}\t|{i6.get()}\t\t|{w6.get()}x{t6.get()}\t|{f6.get()}\t|{a6.get()}\n')
    textarea.insert(END,f'|{mc7.get()}\t|{mm7.get()}\t|{i7.get()}\t\t|{w7.get()}x{t7.get()}\t|{f7.get()}\t|{a7.get()}\n')
    textarea.insert(END,f'|{mc8.get()}\t|{mm8.get()}\t|{i8.get()}\t\t|{w8.get()}x{t8.get()}\t|{f8.get()}\t|{a8.get()}\n')
    textarea.insert(END,f'|{mc9.get()}\t|{mm9.get()}\t|{i9.get()}\t\t|{w9.get()}x{t9.get()}\t|{f9.get()}\t|{a9.get()}\n')
    textarea.insert(END,f'|{mc10.get()}\t|{mm10.get()}\t|{i10.get()}\t\t|{w10.get()}x{t10.get()}\t|{f10.get()}\t|{a10.get()}\n')
    textarea.insert(END,f'|{mc11.get()}\t|{mm11.get()}\t|{i11.get()}\t\t|{w11.get()}x{t11.get()}\t|{f11.get()}\t|{a11.get()}\n')
    textarea.insert(END,f'|{mc12.get()}\t|{mm12.get()}\t|{i12.get()}\t\t|{w12.get()}x{t12.get()}\t|{f12.get()}\t|{a12.get()}\n')
    textarea.insert(END,f'|{mc13.get()}\t|{mm13.get()}\t|{i13.get()}\t\t|{w13.get()}x{t13.get()}\t|{f13.get()}\t|{a13.get()}\n')
    textarea.insert(END,f'|{mc14.get()}\t|{mm14.get()}\t|{i14.get()}\t\t|{w14.get()}x{t14.get()}\t|{f14.get()}\t|{a14.get()}\n')
    textarea.insert(END,f'|{mc15.get()}\t|{mm15.get()}\t|{i15.get()}\t\t|{w15.get()}x{t15.get()}\t|{f15.get()}\t|{a15.get()}\n')
    textarea.insert(END,f'|{mc16.get()}\t|{mm16.get()}\t|{i16.get()}\t\t|{w16.get()}x{t16.get()}\t|{f16.get()}\t|{a16.get()}\n')
    """
    
    textarea.insert(END, f"=============================================================\n")
    textarea.insert(END,f'|{Total1.get()}\t\t              ==TOTAL==      \t\t|{Total2.get()}\t|{Total3.get()}\n')
    textarea.insert(END,f'_____________________________________________________________________\n')
    
    
def print():
    q=textarea.get("1.0","end-1c")
    filename=tempfile.mktemp(".txt")
    open(filename,"w").write(q)
    os.startfile(filename,"print")


def reset():
    textarea.delete(1.0,END)
        
    Bread.set('')
    Total2.set(0)
    Total3.set(0)
    Total1.set(0)

    Date.set('')
    Month.set('')
    Year.set('')
    mc1.set(0)
    mc2.set(0)
    mc3.set(0)
    mc4.set(0)
    mc5.set(0)
    mc6.set(0)
    mc7.set(0)
    mc8.set(0)
    mc9.set(0)
    mc10.set(0)
    mc11.set(0)
    mc12.set(0)
    mc13.set(0)
    mc14.set(0)
    mc15.set(0)
    mc16.set(0)

    f1.set(0)
    f2.set(0)
    f3.set(0)
    f4.set(0)
    f5.set(0)
    f6.set(0)
    f7.set(0)
    f8.set(0)
    f9.set(0)
    f10.set(0)
    f11.set(0)
    f12.set(0)
    f13.set(0)
    f14.set(0)
    f15.set(0)
    f16.set(0)

    a1.set(0)
    a2.set(0)
    a3.set(0)
    a4.set(0)
    a5.set(0)
    a6.set(0)
    a7.set(0)
    a8.set(0)
    a9.set(0)
    a10.set(0)
    a11.set(0)
    a12.set(0)
    a13.set(0)
    a14.set(0)
    a15.set(0)
    a16.set(0)

    w1.set(0)
    w2.set(0)
    w3.set(0)
    w4.set(0)
    w5.set(0)
    w6.set(0)
    w7.set(0)
    w8.set(0)
    w9.set(0)
    w10.set(0)
    w11.set(0)
    w12.set(0)
    w13.set(0)
    w14.set(0)
    w15.set(0)
    w16.set(0)

    t1.set(0)
    t2.set(0)
    t3.set(0)
    t4.set(0)
    t5.set(0)
    t6.set(0)
    t7.set(0)
    t8.set(0)
    t9.set(0)
    t10.set(0)
    t11.set(0)
    t12.set(0)
    t13.set(0)
    t14.set(0)
    t15.set(0)
    t16.set(0)

    i1.set('')
    i2.set('')
    i3.set('')
    i4.set('')
    i5.set('')
    i6.set('')
    i7.set('')
    i8.set('')
    i9.set('')
    i10.set('')
    i11.set('')
    i12.set('')
    i13.set('')
    i14.set('')
    i15.set('')
    i16.set('')

    mm1.set(0)
    mm2.set(0)
    mm3.set(0)
    mm4.set(0)
    mm5.set(0)
    mm6.set(0)
    mm7.set(0)
    mm8.set(0)
    mm9.set(0)
    mm10.set(0)
    mm11.set(0)
    mm12.set(0)
    mm13.set(0)
    mm14.set(0)
    mm15.set(0)
    mm16.set(0)
    total_cost.set('')

def exit():
    if messagebox.askyesno('Exit','Do you really want to exit'):
        root.destroy()

title=Label(root,pady=2,text="|| Sri Ganeshaya Namaha ||                     || Sri Siddhanath Prasanna ||",bd=8,bg='#3f3f3f',fg='white',font=('times new roman',12 ,'bold'),relief=GROOVE,justify=CENTER)
title.pack(fill=X)

#===============Product Details=================
F1 = LabelFrame(root, text=' Enter Product Details', font=('times new roman', 16,'bold'), fg='#2092cb',bg='#3f3f3f',bd=4,relief=GROOVE)
F1.place(x=1, y=43,width=735,height=570)

#=====================Heading==========================
itm=Label(F1, text=' |   MC   |  MC/kg. |                Items Name              |  Wgt  x  touch |   Fine  | Amount |', font=('Times new roman',16, 'bold'), fg='#ea605b',bg='#3f3f3f')
itm.place(x=1,y=29)
n=Label(F1, text='¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯', font=('Helvetic',10, 'bold'), fg='#ea605b',bg='#3f3f3f')
n.place(x=1,y=492)
'''
cost=Label(F1, text='Cost of Items', font=('Helvetic',10, 'bold','underline'), fg='black',bg=bg_color)
cost.grid(row=0,column=2,padx=30,pady=15)
'''
#===============Product============

bread=Label(F1, text='C Name :', font=('times new roman',14,'bold'), fg='#2092cb',bg='#3f3f3f')
bread.place(x=3,y=3)
b_txt=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Bread,justify=CENTER)
b_txt.place(x=88,y=3,height=28,width=200 )
Date1=Label(F1, text='Date :', font=('times new roman',14, 'bold'), fg='#2092cb',bg='#3f3f3f')
Date1.place(x=510,y=3)
Date_txt=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Date,justify=CENTER)
Date_txt.place(height=28,width=45,x=570,y=3)
Month_txt=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Month,justify=CENTER)
Month_txt.place(height=28,width=45,x=620,y=3)
Year_txt=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Year,justify=CENTER)
Year_txt.place(height=28,width=55,x=670,y=3)

#Creating MC table
m1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc1,justify=CENTER,bg='black',fg='white')
m1.place(height=28,width=65,x=8,y=60)
m2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc2,justify=CENTER,bg='black',fg='white')
m2.place(height=28,width=65,x=8,y=87)
m3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc3,justify=CENTER,bg='black',fg='white')
m3.place(height=28,width=65,x=8,y=114)
m4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc4,justify=CENTER,bg='black',fg='white')
m4.place(height=28,width=65,x=8,y=141)
m5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc5,justify=CENTER,bg='black',fg='white')
m5.place(height=28,width=65,x=8,y=168)
m6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc6,justify=CENTER,bg='black',fg='white')
m6.place(height=28,width=65,x=8,y=195)
m7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc7,justify=CENTER,bg='black',fg='white')
m7.place(height=28,width=65,x=8,y=219)
m8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc8,justify=CENTER,bg='black',fg='white')
m8.place(height=28,width=65,x=8,y=246)
m9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc9,justify=CENTER,bg='black',fg='white')
m9.place(height=28,width=65,x=8,y=273)
m10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc10,justify=CENTER,bg='black',fg='white')
m10.place(height=28,width=65,x=8,y=300)
m11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc11,justify=CENTER,bg='black',fg='white')
m11.place(height=28,width=65,x=8,y=327)
m12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc12,justify=CENTER,bg='black',fg='white')
m12.place(height=28,width=65,x=8,y=354)
m13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc13,justify=CENTER,bg='black',fg='white')
m13.place(height=28,width=65,x=8,y=381)
m14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc14,justify=CENTER,bg='black',fg='white')
m14.place(height=28,width=65,x=8,y=408)
m15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc15,justify=CENTER,bg='black',fg='white')
m15.place(height=28,width=65,x=8,y=435)
m16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mc16,justify=CENTER,bg='black',fg='white')
m16.place(height=28,width=65,x=8,y=462)


#creating Fine table

fz1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f1,justify=CENTER,bg='black',fg='white')
fz1.place(height=28,width=68,x=568,y=60)
fz2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f2,justify=CENTER,bg='black',fg='white')
fz2.place(height=28,width=68,x=568,y=87)
fz3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f3,justify=CENTER,bg='black',fg='white')
fz3.place(height=28,width=68,x=568,y=114)
fz4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f4,justify=CENTER,bg='black',fg='white')
fz4.place(height=28,width=68,x=568,y=141)
fz5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f5,justify=CENTER,bg='black',fg='white')
fz5.place(height=28,width=68,x=568,y=168)
fz6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f6,justify=CENTER,bg='black',fg='white')
fz6.place(height=28,width=68,x=568,y=195)
fz7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f7,justify=CENTER,bg='black',fg='white')
fz7.place(height=28,width=68,x=568,y=219)
fz8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f8,justify=CENTER,bg='black',fg='white')
fz8.place(height=28,width=68,x=568,y=246)
fz9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f9,justify=CENTER,bg='black',fg='white')
fz9.place(height=28,width=68,x=568,y=273)
fz10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f10,justify=CENTER,bg='black',fg='white')
fz10.place(height=28,width=68,x=568,y=300)
fz11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f11,justify=CENTER,bg='black',fg='white')
fz11.place(height=28,width=68,x=568,y=327)
fz12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f12,justify=CENTER,bg='black',fg='white')
fz12.place(height=28,width=68,x=568,y=354)
fz13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f13,justify=CENTER,bg='black',fg='white')
fz13.place(height=28,width=68,x=568,y=381)
fz14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f14,justify=CENTER,bg='black',fg='white')
fz14.place(height=28,width=68,x=568,y=408)
fz15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f15,justify=CENTER,bg='black',fg='white')
fz15.place(height=28,width=68,x=568,y=435)
fz16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=f16,justify=CENTER,bg='black',fg='white')
fz16.place(height=28,width=68,x=568,y=462)

#creating Amount Table
az1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a1,justify=CENTER,bg='black',fg='white')
az1.place(height=28,width=81,x=642,y=60)
az2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a2,justify=CENTER,bg='#aed9f8',fg='black')
az2.place(height=28,width=81,x=642,y=87)
az3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a3,justify=CENTER,bg='black',fg='white')
az3.place(height=28,width=81,x=642,y=114)
az4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a4,justify=CENTER,bg='#aed9f8',fg='black')
az4.place(height=28,width=81,x=642,y=141)
az5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a5,justify=CENTER,bg='black',fg='white')
az5.place(height=28,width=81,x=642,y=168)
az6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a6,justify=CENTER,bg='#aed9f8',fg='black')
az6.place(height=28,width=81,x=642,y=195)
az7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a7,justify=CENTER,bg='black',fg='white')
az7.place(height=28,width=81,x=642,y=219)
az8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a8,justify=CENTER,bg='#aed9f8',fg='black')
az8.place(height=28,width=81,x=642,y=246)
az9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a9,justify=CENTER,bg='black',fg='white')
az9.place(height=28,width=81,x=642,y=273)
az10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a10,justify=CENTER,bg='#aed9f8',fg='black')
az10.place(height=28,width=81,x=642,y=300)
az11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a11,justify=CENTER,bg='black',fg='white')
az11.place(height=28,width=81,x=642,y=327)
az12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a12,justify=CENTER,bg='#aed9f8',fg='black')
az12.place(height=28,width=81,x=642,y=354)
az13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a13,justify=CENTER,bg='black',fg='white')
az13.place(height=28,width=81,x=642,y=381)
az14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a14,justify=CENTER,bg='#aed9f8',fg='black')
az14.place(height=28,width=81,x=642,y=408)
az15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a15,justify=CENTER,bg='black',fg='white')
az15.place(height=28,width=81,x=642,y=435)
az16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=a16,justify=CENTER,bg='#aed9f8',fg='black')
az16.place(height=28,width=81,x=642,y=462)

#craeting wight table
wg1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w1,justify=CENTER,bg='black',fg='white')
wg1.place(height=28,width=58,x=435,y=60)
wg2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w2,justify=CENTER,bg='black',fg='white')
wg2.place(height=28,width=58,x=435,y=87)
wg3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w3,justify=CENTER,bg='black',fg='white')
wg3.place(height=28,width=58,x=435,y=114)
wg4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w4,justify=CENTER,bg='black',fg='white')
wg4.place(height=28,width=58,x=435,y=141)
wg5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w5,justify=CENTER,bg='black',fg='white')
wg5.place(height=28,width=58,x=435,y=168)
wg6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w6,justify=CENTER,bg='black',fg='white')
wg6.place(height=28,width=58,x=435,y=195)
wg7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w7,justify=CENTER,bg='black',fg='white')
wg7.place(height=28,width=58,x=435,y=219)
wg8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w8,justify=CENTER,bg='black',fg='white')
wg8.place(height=28,width=58,x=435,y=246)
wg9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w9,justify=CENTER,bg='black',fg='white')
wg9.place(height=28,width=58,x=435,y=273)
wg10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w10,justify=CENTER,bg='black',fg='white')
wg10.place(height=28,width=58,x=435,y=300)
wg11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w11,justify=CENTER,bg='black',fg='white')
wg11.place(height=28,width=58,x=435,y=327)
wg12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w12,justify=CENTER,bg='black',fg='white')
wg12.place(height=28,width=58,x=435,y=354)
wg13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w13,justify=CENTER,bg='black',fg='white')
wg13.place(height=28,width=58,x=435,y=381)
wg14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w14,justify=CENTER,bg='black',fg='white')
wg14.place(height=28,width=58,x=435,y=408)
wg15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w15,justify=CENTER,bg='black',fg='white')
wg15.place(height=28,width=58,x=435,y=435)
wg16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=w16,justify=CENTER,bg='black',fg='white')
wg16.place(height=28,width=58,x=435,y=462)

tc1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t1,justify=CENTER,bg='black',fg='white')
tc1.place(height=28,width=58,x=503,y=60)
tc2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t2,justify=CENTER,bg='black',fg='white')
tc2.place(height=28,width=58,x=503,y=87)
tc3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t3,justify=CENTER,bg='black',fg='white')
tc3.place(height=28,width=58,x=503,y=114)
tc4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t4,justify=CENTER,bg='black',fg='white')
tc4.place(height=28,width=58,x=503,y=141)
tc5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t5,justify=CENTER,bg='black',fg='white')
tc5.place(height=28,width=58,x=503,y=168)
tc6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t6,justify=CENTER,bg='black',fg='white')
tc6.place(height=28,width=58,x=503,y=195)
tc7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t7,justify=CENTER,bg='black',fg='white')
tc7.place(height=28,width=58,x=503,y=219)
tc8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t8,justify=CENTER,bg='black',fg='white')
tc8.place(height=28,width=58,x=503,y=246)
tc9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t9,justify=CENTER,bg='black',fg='white')
tc9.place(height=28,width=58,x=503,y=273)
tc10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t10,justify=CENTER,bg='black',fg='white')
tc10.place(height=28,width=58,x=503,y=300)
tc11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t11,justify=CENTER,bg='black',fg='white')
tc11.place(height=28,width=58,x=503,y=327)
tc12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t12,justify=CENTER,bg='black',fg='white')
tc12.place(height=28,width=58,x=503,y=354)
tc13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t13,justify=CENTER,bg='black',fg='white')
tc13.place(height=28,width=58,x=503,y=381)
tc14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t14,justify=CENTER,bg='black',fg='white')
tc14.place(height=28,width=58,x=503,y=408)
tc15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t15,justify=CENTER,bg='black',fg='white')
tc15.place(height=28,width=58,x=503,y=435)
tc16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=t16,justify=CENTER,bg='black',fg='white')
tc16.place(height=28,width=58,x=503,y=462)


it1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i1,justify=CENTER,bg='#aed9f8',fg='black')
it1.place(height=28,width=255,x=170,y=60)
it2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i2,justify=CENTER,bg='black',fg='white')
it2.place(height=28,width=255,x=170,y=87)
it3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i3,justify=CENTER,bg='#aed9f8',fg='black')
it3.place(height=28,width=255,x=170,y=114)
it4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i4,justify=CENTER,bg='black',fg='white')
it4.place(height=28,width=255,x=170,y=141)
it5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i5,justify=CENTER,bg='#aed9f8',fg='black')
it5.place(height=28,width=255,x=170,y=168)
it6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i6,justify=CENTER,bg='black',fg='white')
it6.place(height=28,width=255,x=170,y=195)
it7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i7,justify=CENTER,bg='#aed9f8',fg='black')
it7.place(height=28,width=255,x=170,y=219)
it8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i8,justify=CENTER,bg='black',fg='white')
it8.place(height=28,width=255,x=170,y=246)
it9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i9,justify=CENTER,bg='#aed9f8',fg='black')
it9.place(height=28,width=255,x=170,y=273)
it10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i10,justify=CENTER,bg='black',fg='white')
it10.place(height=28,width=255,x=170,y=300)
it11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i11,justify=CENTER,bg='#aed9f8',fg='black')
it11.place(height=28,width=255,x=170,y=327)
it12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i12,justify=CENTER,bg='black',fg='white')
it12.place(height=28,width=255,x=170,y=354)
it13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i13,justify=CENTER,bg='#aed9f8',fg='black')
it13.place(height=28,width=255,x=170,y=381)
it14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i14,justify=CENTER,bg='black',fg='white')
it14.place(height=28,width=255,x=170,y=408)
it15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i15,justify=CENTER,bg='#aed9f8',fg='black')
it15.place(height=28,width=255,x=170,y=435)
it16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=i16,justify=CENTER,bg='black',fg='white')
it16.place(height=28,width=255,x=170,y=462)

mk1=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm1,justify=CENTER,bg='black',fg='white')
mk1.place(height=28,width=77,x=84,y=60)
mk2=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm2,justify=CENTER,bg='black',fg='white')
mk2.place(height=28,width=77,x=84,y=87)
mk3=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm3,justify=CENTER,bg='black',fg='white')
mk3.place(height=28,width=77,x=84,y=114)
mk4=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm4,justify=CENTER,bg='black',fg='white')
mk4.place(height=28,width=77,x=84,y=141)
mk5=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm5,justify=CENTER,bg='black',fg='white')
mk5.place(height=28,width=77,x=84,y=168)
mk6=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm6,justify=CENTER,bg='black',fg='white')
mk6.place(height=28,width=77,x=84,y=195)
mk7=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm7,justify=CENTER,bg='black',fg='white')
mk7.place(height=28,width=77,x=84,y=219)
mk8=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm8,justify=CENTER,bg='black',fg='white')
mk8.place(height=28,width=77,x=84,y=246)
mk9=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm9,justify=CENTER,bg='black',fg='white')
mk9.place(height=28,width=77,x=84,y=273)
mk10=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm10,justify=CENTER,bg='black',fg='white')
mk10.place(height=28,width=77,x=84,y=300)
mk11=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm11,justify=CENTER,bg='black',fg='white')
mk11.place(height=28,width=77,x=84,y=327)
mk12=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm12,justify=CENTER,bg='black',fg='white')
mk12.place(height=28,width=77,x=84,y=354)
mk13=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm13,justify=CENTER,bg='black',fg='white')
mk13.place(height=28,width=77,x=84,y=381)
mk14=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm14,justify=CENTER,bg='black',fg='white')
mk14.place(height=28,width=77,x=84,y=408)
mk15=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm14,justify=CENTER,bg='black',fg='white')
mk15.place(height=28,width=77,x=84,y=435)
mk16=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=mm16,justify=CENTER,bg='black',fg='white')
mk16.place(height=28,width=77,x=84,y=462)


totalfine=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Total2,justify=CENTER)
totalfine.place(height=30,width=75,x=562,y=501)
totalamnt=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Total3,justify=CENTER)
totalamnt.place(height=30,width=86,x=640,y=501)
totalmc=Entry(F1,font='arial 15 bold',relief=GROOVE,bd=3,textvariable=Total1,justify=CENTER)
totalmc.place(height=30,width=70,x=10,y=501)
ttllabel=Label(F1, text=' == TOTAL == ', font=('Times new roman',18, 'bold'), fg='#ea605b',bg='#3f3f3f')
ttllabel.place(x=250,y=501)


#=====================Bill areea====================
F2=Frame(root,relief=GROOVE,bd=5)
F2.place(x=740,y=45,width=630,height=700)
bill_title=Label(F2,text='RECEIPT',font=("Times New Roman" ,16,'bold'),fg='#2092cb',bg='#3f3f3f',bd=1,relief=GROOVE).pack(fill=X)
scrol_y=Scrollbar(F2,orient=VERTICAL)
scrol_y.pack(side=RIGHT,fill=BOTH)
textarea=Text(F2,height=630,width=750,font=("Times New Roman" ,12),fg='white',bg='black',bd=1,yscrollcommand=scrol_y.set)
textarea.pack(side=LEFT)
scrol_y.config(command=textarea.yview)



#=====================Buttons========================
F3 = LabelFrame(root,  fg='#2092cb',bg='#3f3f3f',bd=8,relief=GROOVE)
F3.place(x=1, y=640,width=742,height=75)

btn1 = Button(F3, text='Total', font=("Times New Roman" ,19,'bold'), padx=1, pady=1, bg='#2092cb',fg='white',width=5,command=total)
btn1.grid(row=0,column=0,padx=27,pady=5)

btn2 = Button(F3, text='Receipt', font=("Times New Roman" ,19,'bold'), padx=1, pady=1, bg='#2092cb',fg='white',width=5,command=receipt)
btn2.grid(row=0,column=1,padx=27,pady=5)

btn3 = Button(F3, text='Print', font=("Times New Roman" ,19,'bold'), padx=1, pady=1, bg='#2092cb',fg='white',width=5,command=print)
btn3.grid(row=0,column=2,padx=27,pady=5)

btn4 = Button(F3, text='Reset', font=("Times New Roman" ,19,'bold'), padx=1, pady=1, bg='#2092cb',fg='white',width=5,command=reset)
btn4.grid(row=0,column=3,padx=27,pady=5)

btn5 = Button(F3, text='Exit', font=("Times New Roman" ,19,'bold'), padx=1, pady=1, bg='#2092cb',fg='white',width=5,command=exit)
btn5.grid(row=0,column=4,padx=27,pady=5)



root.mainloop()